name: csharpapispec package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/strelka-skaut/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build --configuration Release CSharpApiSpec/CSharpApiSpec
      - name: Create the package
        run: dotnet pack --configuration Release CSharpApiSpec/CSharpApiSpec
      - name: Publish the package to GPR
        run: dotnet nuget push CSharpApiSpec/CSharpApiSpec/bin/Release/*.nupkg --skip-duplicate