name: js-api-spec package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
      - run: |
          curl -L -o "$GITHUB_WORKSPACE/js-api-spec/protoc-gen-grpc-web" https://github.com/grpc/grpc-web/releases/download/1.3.1/protoc-gen-grpc-web-1.3.1-linux-x86_64
          chmod +x "$GITHUB_WORKSPACE/js-api-spec/protoc-gen-grpc-web"
          echo "$GITHUB_WORKSPACE/js-api-spec" >> $GITHUB_PATH         
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@strelka-skaut'
      - run: npm ci
        working-directory: ./js-api-spec
      - run: npm run build
        working-directory: ./js-api-spec
      - run: npm publish
        working-directory: ./js-api-spec
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}